export const ALLOWED_CONTRACT_REGISTRY_RESOURCE = "ALLOWED_CONTRACT_REGISTRY_RESOURCE";

export const ADD_CONTRACT_PERMISSION = "ADD_CONTRACT";
export const SWITCH_FLAG_PERMISSION = "SWITCH_FLAG";

export const ALLOWED_CONTRACT_DEP = "ALLOWED_CONTRACT_REGISTRY";
